// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usoesczdyohidgwbjial.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzb2VzY3pkeW9oaWRnd2JqaWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTQzNjQsImV4cCI6MjA2OTgzMDM2NH0.RSbWM43gHB6vRfrzSxaHjuuwXsXbxY3IqRrJi3RbZwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});